POST http://localhost:8081/api/items
Content-Type: application/json

{
    "item": "This is third todo Item"
}

### 
GET http://localhost:8081/api/items
Content-Type: application/json

### 
PATCH http://localhost:8081/api/items/63e6133a423f3a3eb09e32c0
Content-Type: application/json

{
    "item": "Item updated"
}

###
DELETE http://localhost:8081/api/items/63e6133a423f3a3eb09e32c0
Content-Type: application/json